### ISSUE TITLE
Tensor networks are never defined

### ISSUE THREAD

**Issue by gdalle** [TensorBFS/TensorInference.jl#66]
Although I am familiar with the literature on graphical models, I didn't know what a tensor network was, or why the contraction order is important. I had to look up TensorOperations.jl, which in turn redirected me to [this paper](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.90.033315) before I could understand this crucial aspect.

Both in the docs and in the JOSS paper, there needs to be an introduction to tensor networks and why they're harder to handle than it appears

https://github.com/openjournals/joss-reviews/issues/5700

**Comment by mroavi** [comment]
Absolutely, glad you pointed that out. We've added a whole new section in the documentation to introduce tensor networks and explain their connection with probabilistic graphical models. You can check it out here: 
https://tensorbfs.github.io/TensorInference.jl/dev/tensornetwork/.

**Comment by gdalle** [comment]
Cool addition! I'll give some thought to what we can trim from the paper

**Comment by mroavi** [comment]
The paper now includes a short introduction to tensors, contractions, and tensor networks, and it explains why the contraction order is important.

**Comment by GiggleLiu** [comment]
NOTE: The above link to tensor network definition has been updated.
https://tensorbfs.github.io/TensorInference.jl/dev/tensor-networks/

**Comment by gdalle** [comment]
great!

**Comment by gdalle** [comment]
I would just add one sentence to the paper defining a graphical model, before mentioning the treewidth

**Comment by gdalle** [comment]
And mention that tensors are used to represent factors in a probability distribution
