### ISSUE TITLE
Quirks in the hard-core lattice gas example

### ISSUE THREAD

**Issue by gdalle** [TensorBFS/TensorInference.jl#69]
- The $\infty$ sign mean in the energy formula might be a bit confusing, I would find it clearer to express the independent set constraint explicitly (unless the algorithm actually relies on this formulation with an objective barrier?)
- The lattice graphs are really cool but it's hard to distinguish shades of gray alone, could we maybe vary edge thickness too?
- The sampling step at the end returns an empty lattice

https://github.com/openjournals/joss-reviews/issues/5700

**Comment by mroavi** [comment]
Thanks for the suggestions! We've updated the energy formula, fixed the empty lattice issue, and tweaked the lattice graph's edge thickness. It now looks like this:

![image](https://github.com/TensorBFS/TensorInference.jl/assets/19517248/aabbccd3-4fff-4dc6-89df-fc0151b5c537)
