### ISSUE TITLE
How to free some room in the paper?

### ISSUE THREAD

**Issue by gdalle** [TensorBFS/TensorInference.jl#71]
Opening this issue to keep track of what to cut in order to add details for #66 #67 #68

https://github.com/openjournals/joss-reviews/issues/5700

**Comment by gdalle** [comment]
Here are a few sentences I think are dispensable:

> The advantage of supporting generic element types lies in the
ability to solve a variety of problems using the same tensor network
contraction algorithm, simply by varying the element types used.

> A major challenge in developing intelligent systems is the ability to reason
under uncertainty, a challenge that appears in many real-world problems across
various domains, including artificial intelligence, medical diagnosis, computer
vision, computational biology, and natural language processing.

> This process, which can be
thought of as drawing global insights from local observations, is known as
*probabilistic inference*.

> Additionally, they
form the foundation for various algorithms that enable efficient probabilistic
inference.

> To tackle these
challenges, more efficient and scalable inference algorithms are needed.

I would also shorten the usage example

**Comment by mroavi** [comment]
I noticed that the author and reviewer guidelines state that the paper **may** exceed 1000 words:

> The paper should be between 250-1000 words. Authors submitting papers significantly longer than 1000 words may be asked to reduce the length of their paper.

So, if it is OK with you, we can address the issues above without cutting down on the current information.

**Comment by gdalle** [comment]
I don't have much experience as a JOSS reviewer, so I suggest you ask the editor directly in the review thread. Still, I think some content can easily be cut

**Comment by mroavi** [comment]
The editor expressed no concerns about the length of the paper.
