### ISSUE TITLE
Code example in paper

### ISSUE THREAD

**Issue by gdalle** [TensorBFS/TensorInference.jl#76]
There are a few details i don't understand in the code example:
- `In[4]`: when we assume the X-ray is _positive_, why does it correspond to `Dict(7 => 0)`
- `In[7]`: the phrasing is a bit ambiguous, there is only one most probable outcome which has several variables (and by the way, variables 3 and 4 are zero in this one)

https://github.com/openjournals/joss-reviews/issues/5700

**Comment by mroavi** [comment]
Thanks for spotting these! You are right in both cases. We fixed them in the repo's example (https://github.com/TensorBFS/TensorInference.jl/commit/457960f9e1f7589e2f78f522d85e64dcbb11e493)
and in the paper (https://github.com/TensorBFS/TensorInference.jl/commit/8457c6f992a214d5c24f63060faa7bb03a57c786).
