### ISSUE TITLE
JOSS submission: Spelling in reference

### ISSUE THREAD

**Issue by osorensen** [TensorBFS/TensorInference.jl#85]
On lines 70-71, do "Jin Guo Liu" and "Jin-Guo Liu" refer to the same person? If so, please spell consistently, so the references appears as "Liu et al., 2022; Liu et al. 2021".

<img width="1154" alt="image" src="https://github.com/TensorBFS/TensorInference.jl/assets/21175639/a3549597-260b-4a1d-94c6-2a8375e46563">

https://github.com/openjournals/joss-reviews/issues/5700

**Comment by mroavi** [comment]
Nice catch! Should now be fixed by c982b5283b1e4272aa99b600ba5c1ecc9f2ba472.
