### ISSUE TITLE
JOSS submission: Small edits

### ISSUE THREAD

**Issue by osorensen** [TensorBFS/TensorInference.jl#86]
On line 76, I suggest writing "KaHyParBipartite" and "SABipartite" without parentheses:

<img width="1053" alt="image" src="https://github.com/TensorBFS/TensorInference.jl/assets/21175639/39f0d023-8a89-4d59-85cb-3778f240dd47">

https://github.com/openjournals/joss-reviews/issues/5700

**Comment by mroavi** [comment]
Agreed. The clarity can be improved. Here is our attempt: 367f16a808468e5782cb3d35a53b266d04d77b82

**Comment by osorensen** [comment]
Very nice!
