### ISSUE TITLE
JOSS submission: consistent spelling

### ISSUE THREAD

**Issue by osorensen** [TensorBFS/TensorInference.jl#87]
Please choose either "dyspnea" or "dyspnoea", and use it consistently. It seems like "dyspnea" is American English and "dyspnoea" is British English (https://en.wikipedia.org/wiki/Shortness_of_breath), so choose whichever you prefer.

<img width="942" alt="image" src="https://github.com/TensorBFS/TensorInference.jl/assets/21175639/2b49ddad-4dcc-4bfb-8d37-dd3cb551325d">

https://github.com/openjournals/joss-reviews/issues/5700

**Comment by mroavi** [comment]
We'll stick to American English. Here is the fix 8318f064b9b31087d670a06ade57631116cbad81
