### ISSUE TITLE
Capitalize reference

### ISSUE THREAD

**Issue by osorensen** [TensorBFS/TensorInference.jl#88]
Please make sure "Bayesian" is capitalized, by protecting the BibTeX entry with a set of extra curly braces:

<img width="1040" alt="image" src="https://github.com/TensorBFS/TensorInference.jl/assets/21175639/cee8ce8e-df97-4043-bc7f-4a2482cbac2a">

https://github.com/openjournals/joss-reviews/issues/5700

**Comment by mroavi** [comment]
Fixed here 817775dd4f9afe02a5b28d93ffcd0a49087b0a01. We also improved the consistency of the casing of the titles.
